(* Created with the Wolfram Language : www.wolfram.com *)
(2*I)*\[Kappa]*FV[ph1, e]*FV[ph1, f]*MT[a, d]*MT[b, c] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, f]*FV[ph2, e]*MT[a, d]*MT[b, c] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, e]*FV[ph2, f]*MT[a, d]*MT[b, c] + 
 (2*I)*\[Kappa]*FV[ph2, e]*FV[ph2, f]*MT[a, d]*MT[b, c] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph3, e]*MT[a, d]*MT[b, c] + 
 I*\[Kappa]*FV[ph2, f]*FV[ph3, e]*MT[a, d]*MT[b, c] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph3, f]*MT[a, d]*MT[b, c] + 
 I*\[Kappa]*FV[ph2, e]*FV[ph3, f]*MT[a, d]*MT[b, c] + 
 I*\[Kappa]*FV[ph3, e]*FV[ph3, f]*MT[a, d]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph1, f]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, d]*MT[a, e]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, f]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, f]*MT[a, e]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, d]*MT[a, e]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, d]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, f]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, f]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, f]*MT[a, e]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph1, e]*MT[a, f]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, d]*MT[a, f]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, e]*MT[a, f]*MT[b, c] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, e]*MT[a, f]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, d]*MT[a, f]*MT[b, c] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, d]*MT[a, f]*MT[b, c] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, e]*MT[a, f]*MT[b, c] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, e]*MT[a, f]*MT[b, c] - 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, e]*MT[a, f]*MT[b, c] + 
 (2*I)*\[Kappa]*FV[ph1, e]*FV[ph1, f]*MT[a, c]*MT[b, d] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, f]*FV[ph2, e]*MT[a, c]*MT[b, d] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, e]*FV[ph2, f]*MT[a, c]*MT[b, d] + 
 (2*I)*\[Kappa]*FV[ph2, e]*FV[ph2, f]*MT[a, c]*MT[b, d] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph3, e]*MT[a, c]*MT[b, d] + 
 I*\[Kappa]*FV[ph2, f]*FV[ph3, e]*MT[a, c]*MT[b, d] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph3, f]*MT[a, c]*MT[b, d] + 
 I*\[Kappa]*FV[ph2, e]*FV[ph3, f]*MT[a, c]*MT[b, d] + 
 I*\[Kappa]*FV[ph3, e]*FV[ph3, f]*MT[a, c]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph1, f]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, c]*MT[a, e]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, f]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, f]*MT[a, e]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, c]*MT[a, e]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, c]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, f]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, f]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, f]*MT[a, e]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph1, e]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, c]*MT[a, f]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, e]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, e]*MT[a, f]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, c]*MT[a, f]*MT[b, d] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, c]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, e]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, e]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, e]*MT[a, f]*MT[b, d] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph1, f]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, d]*MT[a, c]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, f]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, f]*MT[a, c]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, d]*MT[a, c]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, d]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, f]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, f]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, f]*MT[a, c]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph1, f]*MT[a, d]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, c]*MT[a, d]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, f]*MT[a, d]*MT[b, e] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, f]*MT[a, d]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, c]*MT[a, d]*MT[b, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, c]*MT[a, d]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, f]*MT[a, d]*MT[b, e] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, f]*MT[a, d]*MT[b, e] - 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, f]*MT[a, d]*MT[b, e] + 
 (2*I)*\[Kappa]*FV[ph1, c]*FV[ph1, d]*MT[a, f]*MT[b, e] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph2, c]*MT[a, f]*MT[b, e] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph2, d]*MT[a, f]*MT[b, e] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, d]*MT[a, f]*MT[b, e] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, d]*FV[ph3, c]*MT[a, f]*MT[b, e] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, c]*MT[a, f]*MT[b, e] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, c]*FV[ph3, d]*MT[a, f]*MT[b, e] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, d]*MT[a, f]*MT[b, e] + 
 (2*I)*\[Kappa]*FV[ph3, c]*FV[ph3, d]*MT[a, f]*MT[b, e] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph1, e]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, d]*MT[a, c]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, e]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, e]*MT[a, c]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, d]*MT[a, c]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, d]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, e]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, e]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, e]*MT[a, c]*MT[b, f] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph1, e]*MT[a, d]*MT[b, f] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, c]*MT[a, d]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, e]*MT[a, d]*MT[b, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, e]*MT[a, d]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, c]*MT[a, d]*MT[b, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, c]*MT[a, d]*MT[b, f] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, e]*MT[a, d]*MT[b, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, e]*MT[a, d]*MT[b, f] - 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, e]*MT[a, d]*MT[b, f] + 
 (2*I)*\[Kappa]*FV[ph1, c]*FV[ph1, d]*MT[a, e]*MT[b, f] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph2, c]*MT[a, e]*MT[b, f] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph2, d]*MT[a, e]*MT[b, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, d]*MT[a, e]*MT[b, f] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, d]*FV[ph3, c]*MT[a, e]*MT[b, f] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, c]*MT[a, e]*MT[b, f] + 
 ((3*I)/2)*\[Kappa]*FV[ph1, c]*FV[ph3, d]*MT[a, e]*MT[b, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, d]*MT[a, e]*MT[b, f] + 
 (2*I)*\[Kappa]*FV[ph3, c]*FV[ph3, d]*MT[a, e]*MT[b, f] - 
 (2*I)*\[Kappa]*FV[ph1, e]*FV[ph1, f]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, e]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, f]*MT[a, b]*MT[c, d] - 
 (2*I)*\[Kappa]*FV[ph2, e]*FV[ph2, f]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph1, f]*FV[ph3, e]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph2, f]*FV[ph3, e]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph1, e]*FV[ph3, f]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph2, e]*FV[ph3, f]*MT[a, b]*MT[c, d] - 
 I*\[Kappa]*FV[ph3, e]*FV[ph3, f]*MT[a, b]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, f]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, b]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, f]*MT[a, e]*MT[c, d] + 
 (2*I)*\[Kappa]*FV[ph2, b]*FV[ph2, f]*MT[a, e]*MT[c, d] + 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, b]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, f]*FV[ph3, b]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, f]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, f]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, f]*MT[a, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, e]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, b]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, e]*MT[a, f]*MT[c, d] + 
 (2*I)*\[Kappa]*FV[ph2, b]*FV[ph2, e]*MT[a, f]*MT[c, d] + 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, b]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, e]*FV[ph3, b]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, e]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, e]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, e]*MT[a, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, f]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, a]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, f]*MT[b, e]*MT[c, d] + 
 (2*I)*\[Kappa]*FV[ph2, a]*FV[ph2, f]*MT[b, e]*MT[c, d] + 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, a]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, f]*FV[ph3, a]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, f]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, f]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, f]*MT[b, e]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, e]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, a]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, e]*MT[b, f]*MT[c, d] + 
 (2*I)*\[Kappa]*FV[ph2, a]*FV[ph2, e]*MT[b, f]*MT[c, d] + 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, a]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, e]*FV[ph3, a]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, e]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, e]*MT[b, f]*MT[c, d] + 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, e]*MT[b, f]*MT[c, d] + 
 (2*I)*\[Kappa]*FV[ph1, d]*FV[ph1, f]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, d]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph2, f]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, f]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph3, d]*MT[a, b]*MT[c, e] + 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, d]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, f]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, f]*MT[a, b]*MT[c, e] + 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, f]*MT[a, b]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, f]*MT[a, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph2, b]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, f]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, f]*MT[a, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, b]*MT[a, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, b]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, f]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, f]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, f]*MT[a, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, d]*MT[a, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, b]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, d]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, d]*MT[a, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph3, b]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, b]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, d]*MT[a, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph2, b]*FV[ph3, d]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, d]*MT[a, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, f]*MT[b, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph2, a]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, f]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, f]*MT[b, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, a]*MT[b, d]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, a]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, f]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, f]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, f]*MT[b, d]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, d]*MT[b, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, a]*MT[b, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, d]*MT[b, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, d]*MT[b, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph3, a]*MT[b, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, a]*MT[b, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, d]*MT[b, f]*MT[c, e] - 
 (I/2)*\[Kappa]*FV[ph2, a]*FV[ph3, d]*MT[b, f]*MT[c, e] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, d]*MT[b, f]*MT[c, e] + 
 (2*I)*\[Kappa]*FV[ph1, d]*FV[ph1, e]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, d]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph2, e]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph2, e]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph3, d]*MT[a, b]*MT[c, f] + 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, d]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, e]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, e]*MT[a, b]*MT[c, f] + 
 I*\[Kappa]*FV[ph3, d]*FV[ph3, e]*MT[a, b]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, e]*MT[a, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph2, b]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, e]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, e]*MT[a, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, b]*MT[a, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, b]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, e]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, e]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, e]*MT[a, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, d]*MT[a, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, b]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, d]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, d]*MT[a, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph3, b]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, b]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, d]*MT[a, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph2, b]*FV[ph3, d]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, d]*MT[a, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, e]*MT[b, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph2, a]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, e]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, e]*MT[b, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, a]*MT[b, d]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, a]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, e]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, e]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, e]*MT[b, d]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, d]*MT[b, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, a]*MT[b, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, d]*MT[b, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, d]*MT[b, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph3, a]*MT[b, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, a]*MT[b, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, d]*MT[b, e]*MT[c, f] - 
 (I/2)*\[Kappa]*FV[ph2, a]*FV[ph3, d]*MT[b, e]*MT[c, f] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, d]*MT[b, e]*MT[c, f] + 
 (2*I)*\[Kappa]*FV[ph1, c]*FV[ph1, f]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph2, c]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph2, f]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, f]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, f]*FV[ph3, c]*MT[a, b]*MT[d, e] + 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, c]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, f]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, f]*MT[a, b]*MT[d, e] + 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, f]*MT[a, b]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, f]*MT[a, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph2, b]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, f]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, f]*MT[a, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, b]*MT[a, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, b]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, f]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, f]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, f]*MT[a, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, c]*MT[a, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, b]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, c]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, c]*MT[a, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph3, b]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, b]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, c]*MT[a, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph2, b]*FV[ph3, c]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, c]*MT[a, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, f]*MT[b, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph2, a]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, f]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, f]*MT[b, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, f]*FV[ph3, a]*MT[b, c]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph2, f]*FV[ph3, a]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, f]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, f]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, f]*MT[b, c]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, c]*MT[b, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, a]*MT[b, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, c]*MT[b, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, c]*MT[b, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph3, a]*MT[b, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, a]*MT[b, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, c]*MT[b, f]*MT[d, e] - 
 (I/2)*\[Kappa]*FV[ph2, a]*FV[ph3, c]*MT[b, f]*MT[d, e] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, c]*MT[b, f]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, b]*MT[c, f]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, a]*MT[c, f]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, b]*MT[c, f]*MT[d, e] + 
 (2*I)*\[Kappa]*FV[ph2, a]*FV[ph2, b]*MT[c, f]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, a]*MT[c, f]*MT[d, e] + 
 ((3*I)/2)*\[Kappa]*FV[ph2, b]*FV[ph3, a]*MT[c, f]*MT[d, e] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, b]*MT[c, f]*MT[d, e] + 
 ((3*I)/2)*\[Kappa]*FV[ph2, a]*FV[ph3, b]*MT[c, f]*MT[d, e] + 
 (2*I)*\[Kappa]*FV[ph3, a]*FV[ph3, b]*MT[c, f]*MT[d, e] + 
 (2*I)*\[Kappa]*FV[ph1, c]*FV[ph1, e]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph2, c]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph2, e]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, e]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, e]*FV[ph3, c]*MT[a, b]*MT[d, f] + 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, c]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, e]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, e]*MT[a, b]*MT[d, f] + 
 I*\[Kappa]*FV[ph3, c]*FV[ph3, e]*MT[a, b]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, e]*MT[a, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph2, b]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, e]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, e]*MT[a, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, b]*MT[a, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, b]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, e]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, e]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, e]*MT[a, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, c]*MT[a, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, b]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, c]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, c]*MT[a, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph3, b]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, b]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, c]*MT[a, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph2, b]*FV[ph3, c]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph3, b]*FV[ph3, c]*MT[a, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, e]*MT[b, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph2, a]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, e]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, e]*MT[b, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, e]*FV[ph3, a]*MT[b, c]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph2, e]*FV[ph3, a]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, e]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, e]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, e]*MT[b, c]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, c]*MT[b, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, a]*MT[b, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, c]*MT[b, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, c]*MT[b, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph3, a]*MT[b, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, a]*MT[b, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, c]*MT[b, e]*MT[d, f] - 
 (I/2)*\[Kappa]*FV[ph2, a]*FV[ph3, c]*MT[b, e]*MT[d, f] - 
 I*\[Kappa]*FV[ph3, a]*FV[ph3, c]*MT[b, e]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, b]*MT[c, e]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, a]*MT[c, e]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, b]*MT[c, e]*MT[d, f] + 
 (2*I)*\[Kappa]*FV[ph2, a]*FV[ph2, b]*MT[c, e]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, a]*MT[c, e]*MT[d, f] + 
 ((3*I)/2)*\[Kappa]*FV[ph2, b]*FV[ph3, a]*MT[c, e]*MT[d, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, b]*MT[c, e]*MT[d, f] + 
 ((3*I)/2)*\[Kappa]*FV[ph2, a]*FV[ph3, b]*MT[c, e]*MT[d, f] + 
 (2*I)*\[Kappa]*FV[ph3, a]*FV[ph3, b]*MT[c, e]*MT[d, f] - 
 (2*I)*\[Kappa]*FV[ph1, c]*FV[ph1, d]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph2, c]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph2, d]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph2, d]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, c]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, c]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, d]*MT[a, b]*MT[e, f] - 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, d]*MT[a, b]*MT[e, f] - 
 (2*I)*\[Kappa]*FV[ph3, c]*FV[ph3, d]*MT[a, b]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, d]*MT[a, c]*MT[e, f] + 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, b]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, d]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, d]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, b]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, b]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, d]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, d]*MT[a, c]*MT[e, f] + 
 (2*I)*\[Kappa]*FV[ph3, b]*FV[ph3, d]*MT[a, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph1, c]*MT[a, d]*MT[e, f] + 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, b]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, c]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph2, c]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, b]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, b]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, c]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, c]*MT[a, d]*MT[e, f] + 
 (2*I)*\[Kappa]*FV[ph3, b]*FV[ph3, c]*MT[a, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, d]*MT[b, c]*MT[e, f] + 
 (I/2)*\[Kappa]*FV[ph1, d]*FV[ph2, a]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, d]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, d]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, d]*FV[ph3, a]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, d]*FV[ph3, a]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, d]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, d]*MT[b, c]*MT[e, f] + 
 (2*I)*\[Kappa]*FV[ph3, a]*FV[ph3, d]*MT[b, c]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, c]*MT[b, d]*MT[e, f] + 
 (I/2)*\[Kappa]*FV[ph1, c]*FV[ph2, a]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, c]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph2, c]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, c]*FV[ph3, a]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, c]*FV[ph3, a]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, c]*MT[b, d]*MT[e, f] + 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, c]*MT[b, d]*MT[e, f] + 
 (2*I)*\[Kappa]*FV[ph3, a]*FV[ph3, c]*MT[b, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph1, b]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph2, a]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph2, b]*MT[c, d]*MT[e, f] - 
 (2*I)*\[Kappa]*FV[ph2, a]*FV[ph2, b]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, b]*FV[ph3, a]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph2, b]*FV[ph3, a]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph1, a]*FV[ph3, b]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*FV[ph2, a]*FV[ph3, b]*MT[c, d]*MT[e, f] - 
 (2*I)*\[Kappa]*FV[ph3, a]*FV[ph3, b]*MT[c, d]*MT[e, f] - 
 I*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph1, ph1] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph1, ph1] - 
 I*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph1, ph2] - 
 I*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph1, ph2] - 
 I*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph1, ph2] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph1, ph2] - 
 I*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph1, ph2] - 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph1, ph2] - 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph1, ph2] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph1, ph2] - 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph1, ph3] - 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph1, ph3] - 
 I*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph1, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph1, ph3] - 
 I*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph1, ph3] - 
 I*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph1, ph3] - 
 I*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph1, ph3] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph1, ph3] - 
 I*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph2, ph2] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph2, ph2] - 
 I*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph2, ph3] - 
 I*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph2, ph3] - 
 ((3*I)/2)*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph2, ph3] + 
 ((3*I)/2)*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph2, ph3] - 
 ((3*I)/2)*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph2, ph3] - 
 I*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph2, ph3] - 
 I*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph2, ph3] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph2, ph3] - 
 I*\[Kappa]*MT[a, f]*MT[b, e]*MT[c, d]*SP[ph3, ph3] - 
 I*\[Kappa]*MT[a, e]*MT[b, f]*MT[c, d]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, f]*MT[b, d]*MT[c, e]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, d]*MT[b, f]*MT[c, e]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, e]*MT[b, d]*MT[c, f]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, d]*MT[b, e]*MT[c, f]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, f]*MT[b, c]*MT[d, e]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, c]*MT[b, f]*MT[d, e]*SP[ph3, ph3] - 
 I*\[Kappa]*MT[a, b]*MT[c, f]*MT[d, e]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, e]*MT[b, c]*MT[d, f]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, c]*MT[b, e]*MT[d, f]*SP[ph3, ph3] - 
 I*\[Kappa]*MT[a, b]*MT[c, e]*MT[d, f]*SP[ph3, ph3] - 
 I*\[Kappa]*MT[a, d]*MT[b, c]*MT[e, f]*SP[ph3, ph3] - 
 I*\[Kappa]*MT[a, c]*MT[b, d]*MT[e, f]*SP[ph3, ph3] + 
 I*\[Kappa]*MT[a, b]*MT[c, d]*MT[e, f]*SP[ph3, ph3]
